# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

formats:
  - htmlzip
  - epub

python:
  install:
    - requirements: docs-requirements.txt

sphinx:
  fail_on_warning: true
