os: linux
dist: bionic
language: python
python:
- pypy3.6-7.2.0
- 3.6
- 3.6-dev
- 3.7
- 3.7-dev
- 3.8
- 3.8-dev
jobs:
  include:
  - os: osx
    language: generic
    env: MACPYTHON=3.6.8
  - os: osx
    language: generic
    env: MACPYTHON=3.7.7
  - os: osx
    language: generic
    env: MACPYTHON=3.8.1
  - os: linux
    language: python
    python: 3.6
    env: CHECK_DOCS=1
  - os: linux
    language: python
    python: 3.6
    env: CHECK_FORMATTING=1
script:
- ci/travis.sh
