[tool.towncrier]
package = "pytest_trio"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/python-trio/pytest-trio/issues/{issue}>`__"
